### PR TITLE
Remove unused fields in drupal part 3

### PR DESCRIPTION
**Pull request by leonk**
### Context

> Does this issue have a Trello card?

https://trello.com/c/nlWyTuqj/21-remove-unused-fields-in-drupal

### Intent

Splitting this card out into multiple PRs.

This PR removes `field_moj_categories` (this is not being used, the category field being used is actually called `field_moj_top_level_categories` so having two fields causes quite a bit of confusion).

### Considerations

To remove the field, I made sure there was no code implementing it in any enabled module.  Either code was removed, or the module was uninstalled.

The following modules were uninstalled as part of this:
- moj_faq_item
- moj_new_content
- moj_pdf_item
- moj_radio_item
- moj_video_collection
- moj_video_item

None of these modules were providing any functionality that is still in use.

### Checklist

- [ ] This PR contains **only** changes related to the above card
- [ ] Tests have been added/updated to cover the change
- [ ] Documentation has been updated where appropriate
- [ ] Tested in Development

### CODE REVIEW

**Review by LucasCairns — DISMISSED** [review]
LGTM :shipit:

**Comment by leonk** [comment]
[Remove unused fields in Drupal](https://trello.com/c/nlWyTuqj/21-remove-unused-fields-in-drupal)

**Review by LucasCairns — APPROVED** [review]
Re-approving 👍

**Review by LucasCairns — APPROVED** [review]
Still LGTM 👍

**Comment by leonk** [comment]
[Show the full list of available terms on Taxonomy fields](https://trello.com/c/a8EdeNGq/20-show-the-full-list-of-available-terms-on-taxonomy-fields)

**Pull request merged**
