### PR TITLE
Story/LNP-820 recently added hq priority content

### PR DESCRIPTION
**Pull request by Eli-TW**
### Context

> Does this issue have a Jira ticket?

https://dsdmoj.atlassian.net/browse/LNP-820

> If this is an issue, do we have steps to reproduce?

N/A

### Intent

> What changes are introduced by this PR that correspond to the above card?

* Introduces a new role exclusively for the comms team
* Creates a new boolean field to prioritise the 5 main prisoner facing content types
* Restricts access to that field to admin and those with the new comms role
* Defaults the priority field to be set to true when members of the comms role create content
* Adjusts the Recently Added JSON:API resource, and hence the Recently Added section of homepages, to return half prioritised content, half unprioritised content, with the prioritised content showing first. 

> Would this PR benefit from screenshots?

No

### Considerations

> Is there any additional information that would help when reviewing this PR?

No

> Are there any steps required when merging/deploying this PR?

No

### Checklist

- [ ] This PR contains **only** changes related to the above card
- [x] Tests have been added/updated to cover the change
- [ ] Documentation has been updated where appropriate
- [x] Tested in Development

This PR does include some changes not directly associated with the story; since upgrading to PHP 8.3, use of undeclared class properties became deprecated. This raises a lot of noise in test runs, and as we were writing new tests, it was appropriate to add property declarations to remove the deprecation warnings.

Also there was duplicated code in the test classes for a function getJsonApiResponse(). As we needed something similar for the new tests, this was refactored into a trait and the duplicate code removed from all test classes, rather than duplicate the code one more time and exacerbating the problem.

### CODE REVIEW

**Review by sweetymj — DISMISSED** [review]
LGTM.

**Review by psoleckimoj — APPROVED** [review]
LGTM!

**Review by psoleckimoj — COMMENTED** [review]
LGTM, but tbh too much for me to review. I can usually work stuff out when a PR is related to one thing even if I don't know the language so well. Probably better for @sweetymj to approve properly.

**Review by sweetymj — APPROVED** [review]
LGTM.

**Pull request merged**
