### PR TITLE
2017 disable unused drupal modules

### PR DESCRIPTION
**Pull request by leonk**
### Context

> Does this issue have a Trello card?

https://trello.com/c/K10SgNy8/6-disable-unused-drupal-modules

### Intent

Disabled modules that were obviously not being used.  I.e. there may be more that _could_ be disabled, but these were the low hanging fruit.

### Considerations

Possibly disabling the language module could have an impact, and we should ensure all of the content endpoints still work correctly (I checked this on local, but should also be done on dev/stagin).

### Checklist

- [ ] This PR contains **only** changes related to the above card
- [ ] Tests have been added/updated to cover the change
- [ ] Documentation has been updated where appropriate
- [ ] Tested in Development

### CODE REVIEW

**Comment by leonk** [comment]
[Disable unused Drupal modules](https://trello.com/c/K10SgNy8/6-disable-unused-drupal-modules)

**Review by LucasCairns — DISMISSED** [review]
LGTM 👍

**Comment by leonk** [comment]
Added a few more to uninstall, but should be good to review+merge now.

**Review by LucasCairns — APPROVED** [review]
👍

**Pull request merged**
