### PR TITLE
For secondary_tags don't send back tags with no content

### PR DESCRIPTION
**Pull request by psoleckimoj**

### CODE REVIEW

**Review by LucasCairns — APPROVED** [review]
LGTM 👍

**Review by spikeheap — CHANGES_REQUESTED** [review]
Looks good 👍  could we add tests around all this please?

**Comment by spikeheap** [comment]
For posterity, here's the Trello card we're tracking this under: https://trello.com/c/08RQ0wq1/1721-remove-empty-secondary-tags-from-all-topics-page

**Comment by psoleckimoj** [comment]
We are going to tests next week. This has visually been checked and since writing the most. simple tests is currently taking 2+ days it's now holding up work.

**Pull request closed without merging**
